### ISSUE TITLE
Tracker: ocular-gatsby v1.1+

### ISSUE THREAD

**Issue by ibgreen** [uber-web/ocular#145]
## v1.2 REFINED OCULAR GATSBY VERSION

For: vis-academy

- [ ] Update CLI script
- [ ] SEO Component - Update or cut

## v1.1 REFINED OCULAR GATSBY VERSION

For: deck.gl/react-map-gl/react-vis

- [ ] Embedded Components (P1, @jckr)
- [ ] Footer: Add back the removed footer (P2, @jckr)
- [ ] Examples:
   - [ ] add an Examples home page (P1 @jckr)
   - [ ] support examples sections (P2 @jckr)
   - [ ] make examples searchable (P2 @jckr)
- [ ] Styling
   - [ ] Responsive styling (P1, @jckr)
   - [ ] global styling / typography pass (P1, @jckr)
   - [ ] determine strategy on where styling information should be and how style can be customized (P2)
- [ ] Header
   - [ ] Load github stars (P1, @jckr)
   - [ ] make links customizable via config (P1, @jckr)
   - [ ] investigate docsearch integration (P1, @jckr)
   - [ ] Restore opacity (P2, @jckr)
- [ ] Inject Webpack config to support `StaticQuery` and `graphql` "fragment" in components without copying files into user website - (P1, TBD)
