### ISSUE TITLE
Tracker: ocular gatsby port

### ISSUE THREAD

**Issue by ibgreen** [uber-web/ocular#74]
Punch List for completing the port of ocular into a gatsby based static website generator for Uber front-end frameworks.

## v1.x REFINED OCULAR GATSBY VERSION

- [ ] Update CLI script
- [ ] SEO Component - Update or cut

## v1.x REFINED OCULAR GATSBY VERSION

- [ ] Table of Contents: Fix expand/collapse behavior P1 (TBD)
- [ ] Footer: Add back P1 (TBD)
- [ ] Header: Load github stars P1 (TBD)
- [ ] Header: restore opacity P2 (TBD)

## v1.0 INITIAL OCULAR GATSBY VERSION

- [ ] Markdown Docs Styling - choose right markdown styling, code, tables, etc. P0 (@jckr)
- [ ] P0 - Fix `StaticQuery` and `graphql` "fragment" support in components - P0 (TBD)
- [x] Implement gatsby "layout" solution to keep common components loaded (e.g. keep TOC scroll state fixed when switching pages) P0 (@ibgreen)
- [x] Implement example loading and example index generation
- [x] Implement markdown processing and table of contents generation
- [x] Support import/export in `gatsby-node` (@ibgreen)
- [x] Redefine ocular as a preset config and page processing/generation package for Gatsby (@ibgreen)

### v0.7 OCULAR CLASSIC

- [ ] Verify that the classic (0.x) versions can still be built and published from `modules/classic` in case we need any maintenance fixes P0 (@jckr)

**Comment by jckr** [comment]
with #101 closed we have finished the work for v1.0. 
I don't know how fast #100 can be resolved as I'm not super well-versed in webpack. Also this doesn't look like it's blocking.
So, going forward I will focus on:
#109 - using the same approach as for the links. Right now, markdown is turned into HTML then href attributes of links are overridden so they resolve. Using the same process we can replace tokens that refer to an embeddable component. This approach is similar to what was used in legacy Ocular. 
#110 - styling through styled components. Once this is done this will make working with ocular and troubleshooting much easier.
