### ISSUE TITLE
Tracker: dev-tools module

### ISSUE THREAD

**Issue by ibgreen** [uber-web/ocular#79]
- [x] auto-detect monorepo: In scripts, test for presence of `modules` dir: `if [ -d "$DIRECTORY" ]; then` instead of double scripts.
- [x] Finalize support for monorepo modules, integrate with at least one monorepo.
- [x] Use Prettier on docs https://github.com/uber/streetscape.gl/pull/164
- [x] Decide if separate `clean` script is needed.

**Comment by ibgreen** [comment]
@Pessimistress FYI
